# An example of ClusterConfig object with custom VPC ipFamily
# set to ipv6; also without any nodegroups:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-2
  region: us-west-2
  version: "1.21"

vpc:
  ipFamily: IPv6

addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest

iam:
  withOIDC: true

managedNodeGroups: []
